name: Notebook Build

on:
  pull_request:
    branches: [main, spatter-devel]

jobs:
  notebook-tests:
    runs-on: ubuntu-latest 
   
    steps:
      - uses: actions/checkout@v4
            
      - name: Set up Python
        uses: actions/setup-python@v5 
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r notebooks/requirements.txt

      #Run the notebook tests with PyTest
      - name: Test Getting Started Notebook 
        run: |
          cd notebooks && pytest --nbmake GettingStarted.ipynb
